version: '3.5'
services:
  web:
    container_name: flask
    build: .
    depends_on:
      - database
    ports:
      - "8000:8000"

  database:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=example
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql
volumes:
  db_volume: